- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific setup.
  include: "setup_{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"

- include_role:
    name: conga-files
  vars:
    base_path: "{{ apache_config_path }}"
    handlers: [ restart apache ]
    files: "{{ conga_files_paths | select('match', '^(?!mods-available/)') | list }}"
    directories: "{{ conga_directories | select('match', '^(?!mods-available)') | list }}"
