# TODO: Move *.any files to dispatcher.d in AEM definitions
- name: Get installed version of Apache.
  shell: "apachectl -v"
  register: _apache_version

- name: Create apache_version variable.
  set_fact:
    apache_version: "{{ _apache_version.stdout.split()[2].split('/')[1] }}"

- name: Use Include directive for Apache 2.2.
  set_fact:
    _include_directive: Include
  when: "apache_version.split('.')[1] == '2'"

- name: Use IncludeOptional directive for Apache 2.4.
  set_fact:
    _include_directive: IncludeOptional
  when: "apache_version.split('.')[1] == '4'"

- name: Include only *.conf files from conf.d.
  lineinfile:
    dest: "{{ apache_config_path }}/apache2.conf"
    line: '{{ _include_directive }} conf.d/*.conf'
    regexp: '^Include(?:Optional)? conf.d/'
  notify:
    - restart apache

# Make additional Apache modules available before we try to enable them
- include_role:
    name: conga-files
  vars:
    base_path: "{{ apache_config_path }}"
    handlers: [ restart apache ]
    files: "{{ conga_files_paths | select('match', 'mods-available/.*') | list }}"

- name: Enable Apache modules required by CONGA role.
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items: "{{ conga_config.httpd.modules }}"
  when: conga_config.httpd is defined and conga_config.httpd.modules is defined
  notify:
    - restart apache

